
services:
  db:
    image: postgres:14.13
    restart: always
    ports:
      - ${DB_PORTS_DOCKER}
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${CONTAINER_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data

