export const CATALOG_ERRORS = {
  AUTH: {
    USER_NOT_FOUND: 'AUTH_4619',
    USER_NOT_ACTIVE: 'AUTH_9309',
    RESOURCE_UNAUTHORIZED: 'AUTH_7707',
    BAD_CREDENTIALS: 'AUTH_4435',
    ERROR_CREATE_USER: 'AUTH_6547',
    SESSION_NOT_EXIST: 'AUTH_9659',
  },
};
